### PR TITLE
edit templates page to use collections and better screenshot formats

### PR DESCRIPTION
**Pull request by wslack**
Inspiration: https://github.com/18f/federalist-docs/edit/master/pages/about-federalist/example-sites.md

### CODE REVIEW

**Comment by wslack** [comment]
Hmmm. I did something wrong with the margins, not sure what.

**Comment by jseppi** [comment]
maybe you want the `.screenshot` class on the `` instead of on the surrounding `<a>`

**Comment by wslack** [comment]
That doesn't match https://github.com/18f/federalist-docs/edit/master/pages/about-federalist/example-sites.md though...

**Comment by wslack** [comment]
I can ask for help tomorrow

**Pull request merged**
