### PR TITLE
Update docker-compose.yml example

### PR DESCRIPTION
**Pull request by jmhooper**
This file updates the docker-compose.yml example in the "cloud.gov Setup" guide.

For background on this look at coreos/clair#284.

### CODE REVIEW

**Comment by wslack** [comment]
this is fascinating but I don't understand the fix enough to merge!

**Comment by jmhooper** [comment]
Essentially what is happening is that Postgres would start before Clair. Because of this, Clair would attempt to connect to the database, but since the database was not up it would crash.

The fix changes the configuration file to tell the container to restart if it crashes for any reason. With this setup, Clair will be restarted once it fails to connect and crashes. It will do this until the postgres container is awake and Clair is able to connect to it.

**Comment by wslack** [comment]
ah, so this doesn't address the root cause but puts in a process that fixes the outcome

**Comment by jmhooper** [comment]
Yeah, basically. We'd need to wait for a patch from CoreOS to fix the root cause which may be in Clair v2.0 which is a pre-release version right now.

**Pull request merged**
