### PR TITLE
add digitalgov search recommendation

### PR DESCRIPTION
**Pull request by jseppi**
Add recommendation to use DigitalGov search and links to their documentation/registration page.

ref #85 and https://github.com/18F/federalist/issues/392

### CODE REVIEW

**Comment by jseppi** [comment]
I didn't have a good sense for where to put this new page organizational. Right now it is in the "Content Guide" section. I could also see it being placed under "Using Federalist."

**Comment by wslack** [comment]
Do we need any other detail or is this enough? (Is there an example site with this live?)

**Comment by jseppi** [comment]
I was hoping federalist-docs could be the example :)

**Comment by jseppi** [comment]
Pretty sure cloud.gov-docs uses digital gov search, but they're not on federalist.

**Pull request merged**
